// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs6gjsiliHpgf9SpB9uzs1Maxj_Aewi30',
    appId: '1:533604829622:web:f88a5152bc44f871b09917',
    messagingSenderId: '533604829622',
    projectId: 'cash-teisou',
    authDomain: 'cash-teisou.firebaseapp.com',
    storageBucket: 'cash-teisou.firebasestorage.app',
    measurementId: 'G-L7L3R4F8J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfpNwLa-YM4RR7M-cnH0bUVog_cd1H7_c',
    appId: '1:533604829622:android:5bca1c0b4000074bb09917',
    messagingSenderId: '533604829622',
    projectId: 'cash-teisou',
    storageBucket: 'cash-teisou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AoskeiFy4oYHT1XxoKMH91SO7-NhGgo',
    appId: '1:533604829622:ios:0a760c71ae4e387fb09917',
    messagingSenderId: '533604829622',
    projectId: 'cash-teisou',
    storageBucket: 'cash-teisou.firebasestorage.app',
    iosBundleId: 'com.cashteisou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6AoskeiFy4oYHT1XxoKMH91SO7-NhGgo',
    appId: '1:533604829622:ios:0a760c71ae4e387fb09917',
    messagingSenderId: '533604829622',
    projectId: 'cash-teisou',
    storageBucket: 'cash-teisou.firebasestorage.app',
    iosBundleId: 'com.cashteisou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs6gjsiliHpgf9SpB9uzs1Maxj_Aewi30',
    appId: '1:533604829622:web:b6d1b793e0b85370b09917',
    messagingSenderId: '533604829622',
    projectId: 'cash-teisou',
    authDomain: 'cash-teisou.firebaseapp.com',
    storageBucket: 'cash-teisou.firebasestorage.app',
    measurementId: 'G-2R7P5NRQS8',
  );
}
